### ISSUE TITLE
Form State: Saving user progress.

### ISSUE THREAD

**Issue by agreentejada** [SARK-Development-Team/TruckerComp#10]
User progress should be saved if they have to enter any complex data, like names, addresses or phone numbers. There's three approaches to this:
- save state in cookies to be retrieved when the page is loaded (requires that little "We save cookies" warning on the bottom of the screen)
- save state on the server, which is currently not doable, since Github Pages is static
- save state in cache (not exactly sure how?)

Alternatively, biBerk doesn't save state. Instead, it treats the initial form variables as inputs to the server. The server then routes the user to the actual form. It breaks immersion slightly.

**Comment by brhymer** [comment]
The user's form data is now saved in document.cookie.

Upon loading the main-form page, it checks for the existence of a corresponding cookie. If one is in place, it populates the form with the data.

This is not functional on the static page because static pages cannot access cookies, however, it is functional at the temporary heroku app: 
https://truckcompv1.herokuapp.com/

**Comment by brhymer** [comment]
The first form (on the home page) affects the display of the second one (on main-form.html). 

The same cookies-based approach can be used to handle the variable inputs.
